### ISSUE TITLE
Board#print() is malfunctioning

### ISSUE THREAD

**Issue by wouterkistemaker** [NucleusChess/Core#2]
**Description**
Chess board is printed in reversed order vertically, the ranks are printed from 1-8 starting at the top.

**To Reproduce**
1. Go to 'BoardTests.java'
2. Click on 'Run'
3. Open the terminal and see error

**Expected behavior**
Chess board to be printed in the order where files go from A-H horizontally starting left and ranks go from 1-8 vertically starting at the bottom

**Comment by Azoraqua** [comment]
I used [Lichess Editor](https://lichess.org/editor) as reference and in my opinion it seems in the correct format:
https://cdn.azoraqua.com/2021-06-03_18-40-59.png
https://cdn.azoraqua.com/2021-06-03_18-43-00.png

**Comment by wouterkistemaker** [comment]
Try executing the same process with only 1 move and you will see the issue

**Comment by wouterkistemaker** [comment]
Issue solved, recoded the method that was responsible for printing the board thanks @Azoraqua
